from abc import ABC, abstractmethod
from typing import List

import pandas as pd

from app.model.signal import Signal


class Strategy(ABC):

    @abstractmethod
    def run(self, df: pd.DataFrame):
        """Run the strategy on the given DataFrame."""
        pass

    @abstractmethod
    def get_signals(self) -> List[Signal]:
        """Return the list of signals generated by the strategy."""
        pass

    @abstractmethod
    def plot(self, df: pd.DataFrame, title: str = "Strategy Plot", ax=None):
        """Plot the strategy results."""
        pass